# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c2c6f153c1ea2735f16284d134eaab691d4ff68ced1d6ace947fb2e8db5208a6365d9be083be4d2e7b4ec3aaf48214b5accc4d169b4b83cfc7876bb3360f504

test:
  secret_key_base: 450bcb62c4d6766bece902aa15f212c351994d079e4d7f42c57e6a4e87a7f7e217d1a7d156f87782c6c2f3e7399db253c4e43f2611d1bf07f1865621e960e583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
